### ISSUE TITLE
Issue with installing LIS' fork of iGibson while installing the SVL version works

### ISSUE THREAD

**Issue by yichao-liang** [Learning-and-Intelligent-Systems/predicators_behavior#88]
I was installing iGibson following the instructions [here](https://github.com/Learning-and-Intelligent-Systems/predicators_behavior/blob/master/behavior.md) on BCS' OpenMind cluster but it's producing the `ModuleNotFoundError: No module named 'cmake'` error. I'd really appreciate it if you could give any pointer regarding how to fix this! Thanks so much!

The following are my commands:
```
$ conda create -n predicators3 python=3.8
$ conda activate predicators3
$ pip install torch==2.0.1 cmake
$ pip install -e ./iGibson
```

And the following is the error output (where the main issue is with cmake)
```
(predicators3) ycliang at node107 in /om2/user/ycliang/predicators_behavior on master*
$ pip install -e ./iGibson
Obtaining file:///net/vast-storage/scratch/vast/tenenbaum/ycliang/predicators_behavior/iGibson
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting gym>=0.12 (from igibson==2.0.1)
  Using cached gym-0.26.2-py3-none-any.whl
Collecting numpy>=1.16.0 (from igibson==2.0.1)
  Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Collecting scipy>=1.2.1 (from igibson==2.0.1)
  Using cached scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
Collecting pybullet-svl>=3.1.6 (from igibson==2.0.1)
  Using cached pybullet_svl-3.1.6.4-cp38-cp38-linux_x86_64.whl
Collecting transforms3d>=0.3.1 (from igibson==2.0.1)
  Using cached transforms3d-0.4.1-py3-none-any.whl.metadata (2.8 kB)
Collecting opencv-python>=3.4.8 (from igibson==2.0.1)
  Using cached opencv_python-4.8.1.78-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting Pillow>=5.4.0 (from igibson==2.0.1)
  Using cached Pillow-10.1.0-cp38-cp38-manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Requirement already satisfied: networkx>=2.0 in /net/vast-storage/scratch/vast/tenenbaum/ycliang/miniconda3/envs/predicators3/lib/python3.8/site-packages (from igibson==2.0.1) (3.1)
Collecting PyYAML (from igibson==2.0.1)
  Using cached PyYAML-6.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting tqdm (from igibson==2.0.1)
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Collecting freetype-py (from igibson==2.0.1)
  Using cached freetype_py-2.4.0-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.0 MB)
Collecting matplotlib (from igibson==2.0.1)
  Using cached matplotlib-3.7.4-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (5.7 kB)
Collecting cloudpickle (from igibson==2.0.1)
  Using cached cloudpickle-3.0.0-py3-none-any.whl.metadata (7.0 kB)
Collecting aenum (from igibson==2.0.1)
  Using cached aenum-3.1.15-py3-none-any.whl.metadata (3.7 kB)
Collecting GPUtil (from igibson==2.0.1)
  Using cached GPUtil-1.4.0-py3-none-any.whl
Collecting ipython (from igibson==2.0.1)
  Using cached ipython-8.12.3-py3-none-any.whl.metadata (5.7 kB)
Collecting pytest (from igibson==2.0.1)
  Using cached pytest-7.4.3-py3-none-any.whl.metadata (7.9 kB)
Collecting future (from igibson==2.0.1)
  Using cached future-0.18.3-py3-none-any.whl
Collecting trimesh (from igibson==2.0.1)
  Using cached trimesh-4.0.8-py3-none-any.whl.metadata (18 kB)
Collecting sphinx-markdown-tables (from igibson==2.0.1)
  Using cached sphinx_markdown_tables-0.0.17-py3-none-any.whl (28 kB)
Collecting sphinx>=1.8.0 (from igibson==2.0.1)
  Using cached sphinx-7.1.2-py3-none-any.whl.metadata (5.8 kB)
Collecting recommonmark (from igibson==2.0.1)
  Using cached recommonmark-0.7.1-py2.py3-none-any.whl (10 kB)
Collecting sphinx-rtd-theme (from igibson==2.0.1)
  Using cached sphinx_rtd_theme-2.0.0-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting h5py (from igibson==2.0.1)
  Using cached h5py-3.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Collecting gitpython (from igibson==2.0.1)
  Using cached GitPython-3.1.40-py3-none-any.whl.metadata (12 kB)
Collecting py360convert (from igibson==2.0.1)
  Using cached py360convert-0.1.0-py3-none-any.whl
Collecting bddl (from igibson==2.0.1)
  Using cached bddl-3.1.0-py3-none-any.whl
Collecting moviepy (from igibson==2.0.1)
  Using cached moviepy-1.0.3-py3-none-any.whl
Collecting gym-notices>=0.0.4 (from gym>=0.12->igibson==2.0.1)
  Using cached gym_notices-0.0.8-py3-none-any.whl (3.0 kB)
Collecting importlib-metadata>=4.8.0 (from gym>=0.12->igibson==2.0.1)
  Using cached importlib_metadata-7.0.1-py3-none-any.whl.metadata (4.9 kB)
Collecting sphinxcontrib-applehelp (from sphinx>=1.8.0->igibson==2.0.1)
  Using cached sphinxcontrib_applehelp-1.0.4-py3-none-any.whl (120 kB)
Collecting sphinxcontrib-devhelp (from sphinx>=1.8.0->igibson==2.0.1)
  Using cached sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
Collecting sphinxcontrib-jsmath (from sphinx>=1.8.0->igibson==2.0.1)
  Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting sphinxcontrib-htmlhelp>=2.0.0 (from sphinx>=1.8.0->igibson==2.0.1)
  Using cached sphinxcontrib_htmlhelp-2.0.1-py3-none-any.whl (99 kB)
Collecting sphinxcontrib-serializinghtml>=1.1.5 (from sphinx>=1.8.0->igibson==2.0.1)
  Using cached sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl (94 kB)
Collecting sphinxcontrib-qthelp (from sphinx>=1.8.0->igibson==2.0.1)
  Using cached sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
Requirement already satisfied: Jinja2>=3.0 in /net/vast-storage/scratch/vast/tenenbaum/ycliang/miniconda3/envs/predicators3/lib/python3.8/site-packages (from sphinx>=1.8.0->igibson==2.0.1) (3.1.2)
Collecting Pygments>=2.13 (from sphinx>=1.8.0->igibson==2.0.1)
  Using cached pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting docutils<0.21,>=0.18.1 (from sphinx>=1.8.0->igibson==2.0.1)
  Using cached docutils-0.20.1-py3-none-any.whl.metadata (2.8 kB)
Collecting snowballstemmer>=2.0 (from sphinx>=1.8.0->igibson==2.0.1)
  Using cached snowballstemmer-2.2.0-py2.py3-none-any.whl (93 kB)
Collecting babel>=2.9 (from sphinx>=1.8.0->igibson==2.0.1)
  Using cached Babel-2.14.0-py3-none-any.whl.metadata (1.6 kB)
Collecting alabaster<0.8,>=0.7 (from sphinx>=1.8.0->igibson==2.0.1)
  Using cached alabaster-0.7.13-py3-none-any.whl (13 kB)
Collecting imagesize>=1.3 (from sphinx>=1.8.0->igibson==2.0.1)
  Using cached imagesize-1.4.1-py2.py3-none-any.whl (8.8 kB)
Collecting requests>=2.25.0 (from sphinx>=1.8.0->igibson==2.0.1)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting packaging>=21.0 (from sphinx>=1.8.0->igibson==2.0.1)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting jupytext (from bddl->igibson==2.0.1)
  Using cached jupytext-1.16.0-py3-none-any.whl.metadata (12 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython->igibson==2.0.1)
  Using cached gitdb-4.0.11-py3-none-any.whl.metadata (1.2 kB)
Collecting backcall (from ipython->igibson==2.0.1)
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting decorator (from ipython->igibson==2.0.1)
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting jedi>=0.16 (from ipython->igibson==2.0.1)
  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting matplotlib-inline (from ipython->igibson==2.0.1)
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting pickleshare (from ipython->igibson==2.0.1)
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 (from ipython->igibson==2.0.1)
  Using cached prompt_toolkit-3.0.43-py3-none-any.whl.metadata (6.5 kB)
Collecting stack-data (from ipython->igibson==2.0.1)
  Using cached stack_data-0.6.3-py3-none-any.whl.metadata (18 kB)
Collecting traitlets>=5 (from ipython->igibson==2.0.1)
  Using cached traitlets-5.14.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: typing-extensions in /net/vast-storage/scratch/vast/tenenbaum/ycliang/miniconda3/envs/predicators3/lib/python3.8/site-packages (from ipython->igibson==2.0.1) (4.9.0)
Collecting pexpect>4.3 (from ipython->igibson==2.0.1)
  Using cached pexpect-4.9.0-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting contourpy>=1.0.1 (from matplotlib->igibson==2.0.1)
  Using cached contourpy-1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.9 kB)
Collecting cycler>=0.10 (from matplotlib->igibson==2.0.1)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->igibson==2.0.1)
  Using cached fonttools-4.47.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (157 kB)
Collecting kiwisolver>=1.0.1 (from matplotlib->igibson==2.0.1)
  Using cached kiwisolver-1.4.5-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting pyparsing>=2.3.1 (from matplotlib->igibson==2.0.1)
  Using cached pyparsing-3.1.1-py3-none-any.whl.metadata (5.1 kB)
Collecting python-dateutil>=2.7 (from matplotlib->igibson==2.0.1)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting importlib-resources>=3.2.0 (from matplotlib->igibson==2.0.1)
  Using cached importlib_resources-6.1.1-py3-none-any.whl.metadata (4.1 kB)
Collecting decorator (from ipython->igibson==2.0.1)
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting proglog<=1.0.0 (from moviepy->igibson==2.0.1)
  Using cached proglog-0.1.10-py3-none-any.whl (6.1 kB)
Collecting imageio<3.0,>=2.5 (from moviepy->igibson==2.0.1)
  Using cached imageio-2.33.1-py3-none-any.whl.metadata (4.9 kB)
Collecting imageio-ffmpeg>=0.2.0 (from moviepy->igibson==2.0.1)
  Using cached imageio_ffmpeg-0.4.9-py3-none-manylinux2010_x86_64.whl.metadata (1.7 kB)
Collecting iniconfig (from pytest->igibson==2.0.1)
  Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting pluggy<2.0,>=0.12 (from pytest->igibson==2.0.1)
  Using cached pluggy-1.3.0-py3-none-any.whl.metadata (4.3 kB)
Collecting exceptiongroup>=1.0.0rc8 (from pytest->igibson==2.0.1)
  Using cached exceptiongroup-1.2.0-py3-none-any.whl.metadata (6.6 kB)
Collecting tomli>=1.0.0 (from pytest->igibson==2.0.1)
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting commonmark>=0.8.1 (from recommonmark->igibson==2.0.1)
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting markdown>=3.4 (from sphinx-markdown-tables->igibson==2.0.1)
  Using cached Markdown-3.5.1-py3-none-any.whl.metadata (7.1 kB)
Collecting sphinxcontrib-jquery<5,>=4 (from sphinx-rtd-theme->igibson==2.0.1)
  Using cached sphinxcontrib_jquery-4.1-py2.py3-none-any.whl (121 kB)
Collecting pytz>=2015.7 (from babel>=2.9->sphinx>=1.8.0->igibson==2.0.1)
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython->igibson==2.0.1)
  Using cached smmap-5.0.1-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: setuptools in /net/vast-storage/scratch/vast/tenenbaum/ycliang/miniconda3/envs/predicators3/lib/python3.8/site-packages (from imageio-ffmpeg>=0.2.0->moviepy->igibson==2.0.1) (68.2.2)
Collecting zipp>=0.5 (from importlib-metadata>=4.8.0->gym>=0.12->igibson==2.0.1)
  Using cached zipp-3.17.0-py3-none-any.whl.metadata (3.7 kB)
Collecting parso<0.9.0,>=0.8.3 (from jedi>=0.16->ipython->igibson==2.0.1)
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /net/vast-storage/scratch/vast/tenenbaum/ycliang/miniconda3/envs/predicators3/lib/python3.8/site-packages (from Jinja2>=3.0->sphinx>=1.8.0->igibson==2.0.1) (2.1.3)
Collecting ptyprocess>=0.5 (from pexpect>4.3->ipython->igibson==2.0.1)
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython->igibson==2.0.1)
  Using cached wcwidth-0.2.12-py2.py3-none-any.whl.metadata (14 kB)
Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib->igibson==2.0.1)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.25.0->sphinx>=1.8.0->igibson==2.0.1)
  Using cached charset_normalizer-3.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests>=2.25.0->sphinx>=1.8.0->igibson==2.0.1)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.25.0->sphinx>=1.8.0->igibson==2.0.1)
  Using cached urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests>=2.25.0->sphinx>=1.8.0->igibson==2.0.1)
  Using cached certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting markdown-it-py>=1.0.0 (from jupytext->bddl->igibson==2.0.1)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting mdit-py-plugins (from jupytext->bddl->igibson==2.0.1)
  Using cached mdit_py_plugins-0.4.0-py3-none-any.whl.metadata (2.7 kB)
Collecting nbformat (from jupytext->bddl->igibson==2.0.1)
  Using cached nbformat-5.9.2-py3-none-any.whl.metadata (3.4 kB)
Collecting toml (from jupytext->bddl->igibson==2.0.1)
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting executing>=1.2.0 (from stack-data->ipython->igibson==2.0.1)
  Using cached executing-2.0.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting asttokens>=2.1.0 (from stack-data->ipython->igibson==2.0.1)
  Using cached asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting pure-eval (from stack-data->ipython->igibson==2.0.1)
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=1.0.0->jupytext->bddl->igibson==2.0.1)
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting fastjsonschema (from nbformat->jupytext->bddl->igibson==2.0.1)
  Using cached fastjsonschema-2.19.0-py3-none-any.whl.metadata (2.0 kB)
Collecting jsonschema>=2.6 (from nbformat->jupytext->bddl->igibson==2.0.1)
  Using cached jsonschema-4.20.0-py3-none-any.whl.metadata (8.1 kB)
Collecting jupyter-core (from nbformat->jupytext->bddl->igibson==2.0.1)
  Using cached jupyter_core-5.6.0-py3-none-any.whl.metadata (3.4 kB)
Collecting attrs>=22.2.0 (from jsonschema>=2.6->nbformat->jupytext->bddl->igibson==2.0.1)
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat->jupytext->bddl->igibson==2.0.1)
  Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl.metadata (3.0 kB)
Collecting pkgutil-resolve-name>=1.3.10 (from jsonschema>=2.6->nbformat->jupytext->bddl->igibson==2.0.1)
  Using cached pkgutil_resolve_name-1.3.10-py3-none-any.whl (4.7 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat->jupytext->bddl->igibson==2.0.1)
  Using cached referencing-0.32.0-py3-none-any.whl.metadata (2.7 kB)
Collecting rpds-py>=0.7.1 (from jsonschema>=2.6->nbformat->jupytext->bddl->igibson==2.0.1)
  Using cached rpds_py-0.15.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting platformdirs>=2.5 (from jupyter-core->nbformat->jupytext->bddl->igibson==2.0.1)
  Using cached platformdirs-4.1.0-py3-none-any.whl.metadata (11 kB)
Using cached cloudpickle-3.0.0-py3-none-any.whl (20 kB)
Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Using cached opencv_python-4.8.1.78-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (61.7 MB)
Using cached Pillow-10.1.0-cp38-cp38-manylinux_2_28_x86_64.whl (3.6 MB)
Using cached sphinx-7.1.2-py3-none-any.whl (3.2 MB)
Using cached transforms3d-0.4.1-py3-none-any.whl (1.4 MB)
Using cached aenum-3.1.15-py3-none-any.whl (137 kB)
Using cached GitPython-3.1.40-py3-none-any.whl (190 kB)
Using cached h5py-3.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
Using cached ipython-8.12.3-py3-none-any.whl (798 kB)
Using cached matplotlib-3.7.4-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Using cached pytest-7.4.3-py3-none-any.whl (325 kB)
Using cached PyYAML-6.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (736 kB)
Using cached sphinx_rtd_theme-2.0.0-py2.py3-none-any.whl (2.8 MB)
Using cached trimesh-4.0.8-py3-none-any.whl (688 kB)
Using cached Babel-2.14.0-py3-none-any.whl (11.0 MB)
Using cached contourpy-1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (301 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached docutils-0.20.1-py3-none-any.whl (572 kB)
Using cached exceptiongroup-1.2.0-py3-none-any.whl (16 kB)
Using cached fonttools-4.47.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
Using cached gitdb-4.0.11-py3-none-any.whl (62 kB)
Using cached imageio-2.33.1-py3-none-any.whl (313 kB)
Using cached imageio_ffmpeg-0.4.9-py3-none-manylinux2010_x86_64.whl (26.9 MB)
Using cached importlib_metadata-7.0.1-py3-none-any.whl (23 kB)
Using cached importlib_resources-6.1.1-py3-none-any.whl (33 kB)
Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
Using cached kiwisolver-1.4.5-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
Using cached Markdown-3.5.1-py3-none-any.whl (102 kB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached pexpect-4.9.0-py2.py3-none-any.whl (63 kB)
Using cached pluggy-1.3.0-py3-none-any.whl (18 kB)
Using cached prompt_toolkit-3.0.43-py3-none-any.whl (386 kB)
Using cached pygments-2.17.2-py3-none-any.whl (1.2 MB)
Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached traitlets-5.14.0-py3-none-any.whl (85 kB)
Using cached jupytext-1.16.0-py3-none-any.whl (152 kB)
Using cached stack_data-0.6.3-py3-none-any.whl (24 kB)
Using cached asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Using cached charset_normalizer-3.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
Using cached executing-2.0.1-py2.py3-none-any.whl (24 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
Using cached smmap-5.0.1-py3-none-any.whl (24 kB)
Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Using cached zipp-3.17.0-py3-none-any.whl (7.4 kB)
Using cached mdit_py_plugins-0.4.0-py3-none-any.whl (54 kB)
Using cached nbformat-5.9.2-py3-none-any.whl (77 kB)
Using cached wcwidth-0.2.12-py2.py3-none-any.whl (34 kB)
Using cached jsonschema-4.20.0-py3-none-any.whl (84 kB)
Using cached fastjsonschema-2.19.0-py3-none-any.whl (23 kB)
Using cached jupyter_core-5.6.0-py3-none-any.whl (28 kB)
Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
Using cached platformdirs-4.1.0-py3-none-any.whl (17 kB)
Using cached referencing-0.32.0-py3-none-any.whl (26 kB)
Using cached rpds_py-0.15.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
Building wheels for collected packages: igibson
  Building editable for igibson (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building editable for igibson (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [117 lines of output]
      running editable_wheel
      creating /tmp/pip-wheel-h2q8mohk/.tmp-4o9dj19o/igibson.egg-info
      writing /tmp/pip-wheel-h2q8mohk/.tmp-4o9dj19o/igibson.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-wheel-h2q8mohk/.tmp-4o9dj19o/igibson.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-wheel-h2q8mohk/.tmp-4o9dj19o/igibson.egg-info/requires.txt
      writing top-level names to /tmp/pip-wheel-h2q8mohk/.tmp-4o9dj19o/igibson.egg-info/top_level.txt
      writing manifest file '/tmp/pip-wheel-h2q8mohk/.tmp-4o9dj19o/igibson.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-wheel-h2q8mohk/.tmp-4o9dj19o/igibson.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-wheel-h2q8mohk/.tmp-4o9dj19o/igibson.egg-info/SOURCES.txt'
      creating '/tmp/pip-wheel-h2q8mohk/.tmp-4o9dj19o/igibson-2.0.1.dist-info'
      creating /tmp/pip-wheel-h2q8mohk/.tmp-4o9dj19o/igibson-2.0.1.dist-info/WHEEL
      running build_py
      running build_ext
      Traceback (most recent call last):
        File "/om2/user/ycliang/miniconda3/envs/predicators3/bin/cmake", line 5, in <module>
          from cmake import cmake
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 156, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 345, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 268, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 295, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 44, in run
        File "/om2/user/ycliang/miniconda3/envs/predicators3/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/om2/user/ycliang/miniconda3/envs/predicators3/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
      /tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py:988: _DebuggingTips: Problem in editable installation.
      !!

              ********************************************************************************
              An error happened while installing `igibson` in editable mode.

              The following steps are recommended to help debug this problem:

              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.

              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:

                  https://github.com/pypa/setuptools/issues

              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************

      !!
        cmd_obj.run()
      Traceback (most recent call last):
        File "/om2/user/ycliang/miniconda3/envs/predicators3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/om2/user/ycliang/miniconda3/envs/predicators3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/om2/user/ycliang/miniconda3/envs/predicators3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 273, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 436, in build_editable
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 127, in <module>
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 156, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 345, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 268, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 295, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-ateioi2h/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 44, in run
        File "/om2/user/ycliang/miniconda3/envs/predicators3/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/om2/user/ycliang/miniconda3/envs/predicators3/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for igibson
Failed to build igibson
ERROR: Could not build wheels for igibson, which is required to install pyproject.toml-based projects
```

**Comment by shaoyifei96** [comment]
I had this issue. make sure you install cmake in conda instead.
`conda install -c conda-forge cmake`
